-- Auto-generated structural + reference-data clone of the
-- `student` schema from the knowledge-base Supabase project
-- (jypckdqtrqbriogrnnzi), applied to the conversation-storage
-- project (CONVERSATION_DATABASE_URL) as a sandbox for testing
-- integration before touching the source schema. Generated by
-- introspecting information_schema/pg_catalog — do not hand-edit;
-- regenerate instead if the source schema changes.

create schema if not exists student;

create table student.academic_departments (
  department_id uuid not null default gen_random_uuid(),
  department_code varchar(50),
  department_name varchar(255),
  faculty_id uuid,
  constraint academic_departments_pkey primary key (department_id)
);

create table student.academic_progress (
  progress_id uuid not null default gen_random_uuid(),
  student_id uuid,
  current_gpa numeric(3,2),
  cumulative_gpa numeric(3,2),
  credits_completed integer,
  credits_remaining integer,
  risk_level varchar(20),
  constraint academic_progress_pkey primary key (progress_id)
);

create table student.admission_offers (
  offer_id uuid not null default gen_random_uuid(),
  application_id uuid,
  offer_type varchar(100),
  offer_date date,
  expiry_date date,
  acceptance_status varchar(50),
  scholarship_amount numeric(12,2),
  constraint admission_offers_pkey primary key (offer_id),
  constraint admission_offers_application_id_key unique (application_id)
);

create table student.agent_actions (
  action_id uuid not null default gen_random_uuid(),
  run_id uuid,
  action_type varchar(100),
  action_name varchar(255),
  action_reason text,
  priority varchar(50),
  status varchar(50),
  failure_reason text,
  constraint agent_actions_pkey primary key (action_id)
);

create table student.agent_runs (
  run_id uuid not null default gen_random_uuid(),
  conversation_id uuid,
  user_id uuid,
  model_provider varchar(100),
  model_name varchar(100),
  run_type varchar(100),
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  confidence_score numeric(5,2),
  run_status varchar(50),
  constraint agent_runs_pkey primary key (run_id)
);

create table student.alumni_profiles (
  alumni_profile_id uuid not null default gen_random_uuid(),
  student_id uuid,
  graduation_year integer,
  current_employer varchar(255),
  job_title varchar(255),
  industry varchar(255),
  mentorship_available boolean default false,
  constraint alumni_profiles_pkey primary key (alumni_profile_id),
  constraint alumni_profiles_student_id_key unique (student_id)
);

create table student.application_documents (
  document_id uuid not null default gen_random_uuid(),
  application_id uuid,
  document_type varchar(100),
  document_name varchar(255),
  storage_path text,
  verification_status varchar(50),
  uploaded_at timestamp with time zone default now(),
  constraint application_documents_pkey primary key (document_id)
);

create table student.applications (
  application_id uuid not null default gen_random_uuid(),
  student_id uuid,
  program_id uuid,
  application_no varchar(50),
  application_type varchar(50),
  admission_term varchar(50),
  submission_date timestamp with time zone,
  status varchar(50),
  application_score numeric(5,2),
  review_notes text,
  final_decision varchar(50),
  constraint applications_pkey primary key (application_id),
  constraint applications_application_no_key unique (application_no)
);

create table student.appointments (
  appointment_id uuid not null default gen_random_uuid(),
  user_id uuid,
  staff_id uuid,
  appointment_type varchar(100),
  appointment_date timestamp with time zone,
  status varchar(50),
  constraint appointments_pkey primary key (appointment_id)
);

create table student.attachments (
  attachment_id uuid not null default gen_random_uuid(),
  message_id uuid,
  file_name varchar(255),
  file_type varchar(100),
  storage_path text,
  constraint attachments_pkey primary key (attachment_id)
);

create table student.career_profiles (
  career_profile_id uuid not null default gen_random_uuid(),
  student_id uuid,
  target_industry varchar(255),
  target_job varchar(255),
  skills text,
  certifications text,
  linkedin_url text,
  career_readiness_score numeric(5,2),
  constraint career_profiles_pkey primary key (career_profile_id)
);

create table student.conversations (
  conversation_id uuid not null default gen_random_uuid(),
  user_id uuid,
  title varchar(255),
  channel varchar(50),
  language varchar(50),
  summary text,
  total_messages integer,
  started_at timestamp with time zone default now(),
  constraint conversations_pkey primary key (conversation_id)
);

create table student.course_departments (
  course_department_id uuid not null default gen_random_uuid(),
  course_id uuid not null,
  department_id uuid not null,
  department_role varchar(50),
  constraint course_departments_pkey primary key (course_department_id),
  constraint course_departments_course_id_department_id_key unique (course_id, department_id)
);

create table student.course_enrolments (
  course_enrolment_id uuid not null default gen_random_uuid(),
  enrolment_id uuid,
  course_id uuid,
  academic_year integer,
  attendance_percentage numeric(5,2),
  coursework_score numeric(5,2),
  exam_score numeric(5,2),
  final_grade varchar(10),
  constraint course_enrolments_pkey primary key (course_enrolment_id)
);

create table student.courses (
  course_id uuid not null default gen_random_uuid(),
  course_code varchar(20),
  course_name varchar(255),
  course_description text,
  credit_hours integer,
  semester_offered varchar(20),
  constraint courses_pkey primary key (course_id),
  constraint courses_course_code_key unique (course_code)
);

create table student.departments (
  department_id uuid not null default gen_random_uuid(),
  department_name varchar(255) not null,
  constraint departments_pkey primary key (department_id),
  constraint departments_department_name_key unique (department_name)
);

create table student.enrolments (
  enrolment_id uuid not null default gen_random_uuid(),
  student_id uuid,
  program_id uuid,
  current_year integer,
  current_semester varchar(20),
  status varchar(50),
  expected_graduation_date date,
  constraint enrolments_pkey primary key (enrolment_id)
);

create table student.faculties (
  faculty_id uuid not null default gen_random_uuid(),
  faculty_code varchar(20),
  faculty_name varchar(255) not null,
  dean_name varchar(255),
  constraint faculties_pkey primary key (faculty_id),
  constraint faculties_faculty_code_key unique (faculty_code)
);

create table student.graduation_audits (
  audit_id uuid not null default gen_random_uuid(),
  student_id uuid,
  required_credits integer,
  completed_credits integer,
  remaining_credits integer,
  graduation_status varchar(50),
  audit_date timestamp with time zone,
  constraint graduation_audits_pkey primary key (audit_id)
);

create table student.job_recommendations (
  recommendation_id uuid not null default gen_random_uuid(),
  career_profile_id uuid,
  job_title varchar(255),
  company_name varchar(255),
  location varchar(255),
  match_score numeric(5,2),
  recommendation_reason text,
  constraint job_recommendations_pkey primary key (recommendation_id)
);

create table student.knowledge_chunks (
  chunk_id uuid not null default gen_random_uuid(),
  knowledge_id uuid,
  chunk_order integer,
  chunk_text text,
  token_count integer,
  constraint knowledge_chunks_pkey primary key (chunk_id)
);

create table student.knowledge_sources (
  knowledge_id uuid not null default gen_random_uuid(),
  title varchar(255),
  source_type varchar(100),
  department_owner varchar(100),
  approval_status varchar(50),
  version_no integer default 1,
  constraint knowledge_sources_pkey primary key (knowledge_id)
);

create table student.messages (
  message_id uuid not null default gen_random_uuid(),
  conversation_id uuid,
  sender_type varchar(50),
  message_text text,
  detected_intent varchar(255),
  sentiment varchar(50),
  token_count integer,
  created_at timestamp with time zone default now(),
  constraint messages_pkey primary key (message_id)
);

create table student.notifications (
  notification_id uuid not null default gen_random_uuid(),
  user_id uuid,
  notification_type varchar(100),
  channel varchar(50),
  title varchar(255),
  message text,
  status varchar(50),
  constraint notifications_pkey primary key (notification_id)
);

create table student.program_courses (
  program_course_id uuid not null default gen_random_uuid(),
  program_id uuid not null,
  course_id uuid not null,
  course_type text,
  constraint program_courses_pkey primary key (program_course_id),
  constraint program_courses_program_id_course_id_key unique (program_id, course_id)
);

create table student.program_departments (
  program_department_id uuid not null default gen_random_uuid(),
  program_id uuid,
  department_id uuid,
  role varchar(50),
  constraint program_departments_pkey primary key (program_department_id)
);

create table student.programs (
  program_id uuid not null default gen_random_uuid(),
  faculty_id uuid,
  program_code varchar(20),
  program_name varchar(255),
  program_level varchar(50),
  duration_years integer,
  total_credit_required integer,
  description text,
  career_outcomes text,
  tuition_fee numeric(12,2),
  status varchar(50),
  constraint programs_pkey primary key (program_id),
  constraint programs_program_code_key unique (program_code)
);

create table student.roles (
  role_id uuid not null default gen_random_uuid(),
  role_name varchar(100) not null,
  description text,
  created_at timestamp with time zone default now(),
  constraint roles_pkey primary key (role_id),
  constraint roles_role_name_key unique (role_name)
);

create table student.staff (
  staff_id uuid not null default gen_random_uuid(),
  user_id uuid,
  department_id uuid,
  employee_no varchar(50),
  job_title varchar(255),
  constraint staff_pkey primary key (staff_id),
  constraint staff_user_id_key unique (user_id)
);

create table student.staff_assignments (
  assignment_id uuid not null default gen_random_uuid(),
  ticket_id uuid,
  staff_id uuid,
  resolution_note text,
  constraint staff_assignments_pkey primary key (assignment_id)
);

create table student.student_profiles (
  student_id uuid not null default gen_random_uuid(),
  user_id uuid,
  student_number varchar(50),
  current_stage varchar(50),
  intake_year integer,
  intake_term varchar(20),
  campus varchar(100),
  study_mode varchar(50),
  citizenship_status varchar(100),
  home_address text,
  emergency_contact_name varchar(255),
  emergency_contact_phone varchar(50),
  program_interest varchar(255),
  student_status varchar(50),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint student_profiles_pkey primary key (student_id),
  constraint student_profiles_student_number_key unique (student_number),
  constraint student_profiles_user_id_key unique (user_id)
);

create table student.support_tickets (
  ticket_id uuid not null default gen_random_uuid(),
  user_id uuid,
  conversation_id uuid,
  department_id uuid,
  category varchar(100),
  priority varchar(50),
  escalation_reason text,
  status varchar(50),
  constraint support_tickets_pkey primary key (ticket_id)
);

create table student.tool_calls (
  tool_call_id uuid not null default gen_random_uuid(),
  action_id uuid,
  tool_name varchar(255),
  tool_version varchar(50),
  request_payload jsonb,
  response_payload jsonb,
  success boolean,
  error_message text,
  constraint tool_calls_pkey primary key (tool_call_id)
);

create table student.user_profiles (
  user_id uuid not null,
  lifecycle_stage varchar(20),
  academic_background_raw text,
  academic_background_std varchar(100),
  tech_level_raw text,
  tech_level_std varchar(20),
  school_tier varchar(50),
  work_years integer,
  gmat integer,
  gre integer,
  toefl integer,
  ielts numeric(3,1),
  target_role_raw text,
  target_role_std varchar(30),
  target_industry_raw text,
  target_industry_std varchar(100),
  application_term varchar(50),
  intake_year integer,
  completed_courses text[] default '{}'::text[],
  asked_topics text[] default '{}'::text[],
  personalization_opt_out boolean default false,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  constraint user_profiles_pkey primary key (user_id),
  constraint user_profiles_lifecycle_stage_check check (((lifecycle_stage)::text = ANY ((ARRAY['prospect'::character varying, 'applicant'::character varying, 'admitted'::character varying, 'enrolled'::character varying, 'alumni'::character varying])::text[]))),
  constraint user_profiles_target_role_std_check check (((target_role_std)::text = ANY ((ARRAY['quant_risk'::character varying, 'data_analytics'::character varying, 'fintech_pm'::character varying, 'payments'::character varying, 'digital_banking'::character varying, 'compliance_regtech'::character varying])::text[]))),
  constraint user_profiles_tech_level_std_check check (((tech_level_std)::text = ANY ((ARRAY['none'::character varying, 'basic'::character varying, 'strong'::character varying])::text[])))
);

create table student.user_roles (
  user_role_id uuid not null default gen_random_uuid(),
  user_id uuid,
  role_id uuid,
  assigned_at timestamp with time zone default now(),
  constraint user_roles_pkey primary key (user_role_id),
  constraint user_roles_user_id_role_id_key unique (user_id, role_id)
);

create table student.users (
  user_id uuid not null default gen_random_uuid(),
  email varchar(255) not null,
  full_name varchar(255) not null,
  preferred_name varchar(255),
  phone_number varchar(50),
  alternate_phone varchar(50),
  date_of_birth date,
  gender varchar(50),
  nationality varchar(100),
  country_of_residence varchar(100),
  profile_photo_url text,
  preferred_language varchar(50),
  preferred_contact_method varchar(50),
  account_status varchar(50),
  email_verified boolean default false,
  phone_verified boolean default false,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint users_pkey primary key (user_id),
  constraint users_email_key unique (email)
);

create table student.workflow_executions (
  workflow_id uuid not null default gen_random_uuid(),
  run_id uuid,
  workflow_name varchar(255),
  workflow_category varchar(100),
  workflow_status varchar(50),
  total_steps integer,
  completed_steps integer,
  constraint workflow_executions_pkey primary key (workflow_id)
);

create table student.workflow_steps (
  step_id uuid not null default gen_random_uuid(),
  workflow_id uuid,
  step_order integer,
  step_name varchar(255),
  step_type varchar(100),
  status varchar(50),
  input_data jsonb,
  output_data jsonb,
  constraint workflow_steps_pkey primary key (step_id)
);

-- Foreign keys
alter table student.academic_departments add constraint fk_academic_department_faculty foreign key (faculty_id) references student.faculties(faculty_id);
alter table student.academic_progress add constraint academic_progress_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.admission_offers add constraint admission_offers_application_id_fkey foreign key (application_id) references student.applications(application_id);
alter table student.agent_actions add constraint agent_actions_run_id_fkey foreign key (run_id) references student.agent_runs(run_id);
alter table student.agent_runs add constraint agent_runs_conversation_id_fkey foreign key (conversation_id) references student.conversations(conversation_id);
alter table student.agent_runs add constraint agent_runs_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.alumni_profiles add constraint alumni_profiles_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.application_documents add constraint application_documents_application_id_fkey foreign key (application_id) references student.applications(application_id);
alter table student.applications add constraint applications_program_id_fkey foreign key (program_id) references student.programs(program_id);
alter table student.applications add constraint applications_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.appointments add constraint appointments_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.appointments add constraint appointments_staff_id_fkey foreign key (staff_id) references student.staff(staff_id);
alter table student.attachments add constraint attachments_message_id_fkey foreign key (message_id) references student.messages(message_id);
alter table student.career_profiles add constraint career_profiles_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.conversations add constraint conversations_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.course_departments add constraint course_departments_department_id_fkey foreign key (department_id) references student.academic_departments(department_id);
alter table student.course_departments add constraint course_departments_course_id_fkey foreign key (course_id) references student.courses(course_id);
alter table student.course_enrolments add constraint course_enrolments_course_id_fkey foreign key (course_id) references student.courses(course_id);
alter table student.course_enrolments add constraint course_enrolments_enrolment_id_fkey foreign key (enrolment_id) references student.enrolments(enrolment_id);
alter table student.enrolments add constraint enrolments_program_id_fkey foreign key (program_id) references student.programs(program_id);
alter table student.enrolments add constraint enrolments_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.graduation_audits add constraint graduation_audits_student_id_fkey foreign key (student_id) references student.student_profiles(student_id);
alter table student.job_recommendations add constraint job_recommendations_career_profile_id_fkey foreign key (career_profile_id) references student.career_profiles(career_profile_id);
alter table student.knowledge_chunks add constraint knowledge_chunks_knowledge_id_fkey foreign key (knowledge_id) references student.knowledge_sources(knowledge_id);
alter table student.messages add constraint messages_conversation_id_fkey foreign key (conversation_id) references student.conversations(conversation_id);
alter table student.notifications add constraint notifications_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.program_courses add constraint fk_course foreign key (course_id) references student.courses(course_id);
alter table student.program_courses add constraint fk_program foreign key (program_id) references student.programs(program_id);
alter table student.program_departments add constraint program_departments_department_id_fkey foreign key (department_id) references student.academic_departments(department_id);
alter table student.program_departments add constraint program_departments_program_id_fkey foreign key (program_id) references student.programs(program_id);
alter table student.programs add constraint programs_faculty_id_fkey foreign key (faculty_id) references student.faculties(faculty_id);
alter table student.staff add constraint staff_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.staff add constraint staff_department_id_fkey foreign key (department_id) references student.departments(department_id);
alter table student.staff_assignments add constraint staff_assignments_staff_id_fkey foreign key (staff_id) references student.staff(staff_id);
alter table student.staff_assignments add constraint staff_assignments_ticket_id_fkey foreign key (ticket_id) references student.support_tickets(ticket_id);
alter table student.student_profiles add constraint student_profiles_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.support_tickets add constraint support_tickets_conversation_id_fkey foreign key (conversation_id) references student.conversations(conversation_id);
alter table student.support_tickets add constraint support_tickets_department_id_fkey foreign key (department_id) references student.departments(department_id);
alter table student.support_tickets add constraint support_tickets_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.tool_calls add constraint tool_calls_action_id_fkey foreign key (action_id) references student.agent_actions(action_id);
alter table student.user_profiles add constraint user_profiles_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.user_roles add constraint user_roles_role_id_fkey foreign key (role_id) references student.roles(role_id);
alter table student.user_roles add constraint user_roles_user_id_fkey foreign key (user_id) references student.users(user_id);
alter table student.workflow_executions add constraint workflow_executions_run_id_fkey foreign key (run_id) references student.agent_runs(run_id);
alter table student.workflow_steps add constraint workflow_steps_workflow_id_fkey foreign key (workflow_id) references student.workflow_executions(workflow_id);

-- Additional indexes
create index idx_applications_student ON student.applications USING btree (student_id);
create index idx_conversations_user ON student.conversations USING btree (user_id);
create index idx_messages_conversation ON student.messages USING btree (conversation_id);
create index idx_user_roles_user ON student.user_roles USING btree (user_id);

-- Reference data (copied from the source schema at generation time)
insert into student.roles (role_id, role_name, description, created_at) values
  ('017e1eab-cff5-45c6-8910-f1683cabeb8d', 'Career Advisor', 'Provides career guidance', '2026-08-04T11:59:08.591557+00:00'),
  ('22d5234e-5a41-4a5d-8278-a1e288d6d74e', 'System Admin', 'Platform administrator', '2026-08-04T11:59:08.591557+00:00'),
  ('313d5132-816e-46cc-a22e-e89e524460f3', 'Prospective Student', 'Potential student exploring programmes', '2026-08-04T11:59:08.591557+00:00'),
  ('3d83d9f8-9482-48c6-93e9-da24d5d45225', 'Graduating Student', 'Student approaching graduation', '2026-08-04T11:59:08.591557+00:00'),
  ('41e4d7e3-52c6-4d72-976c-d78d986549da', 'Program Office', 'Supports programme administration', '2026-08-04T11:59:08.591557+00:00'),
  ('4bc549d9-90ef-4a86-be9c-4940ca09345a', 'Alumni Relations', 'Manages alumni engagement', '2026-08-04T11:59:08.591557+00:00'),
  ('d8d9d3aa-1ed2-4a81-924c-b1997fe08a2e', 'Enrolled Student', 'Active student enrolled in a programme', '2026-08-04T11:59:08.591557+00:00'),
  ('e0597aa5-7abb-45cc-90e2-ea41993b0313', 'Faculty Support', 'Provides academic support', '2026-08-04T11:59:08.591557+00:00'),
  ('ee96e170-8a39-4ccb-bfe2-cc6fef800871', 'Applicant', 'Student who has submitted an application', '2026-08-04T11:59:08.591557+00:00'),
  ('fb105601-8d83-467e-b0be-6967eebe9572', 'Admissions Staff', 'Handles applications and admissions', '2026-08-04T11:59:08.591557+00:00'),
  ('fc8de5f3-d1a0-47b4-9333-f954fa48b99a', 'Alumni', 'Graduate of the university', '2026-08-04T11:59:08.591557+00:00'),
  ('fcbc3b60-3d1d-4e18-86cc-81ed7de3a93a', 'Admitted Student', 'Student who received an admission offer', '2026-08-04T11:59:08.591557+00:00');

insert into student.faculties (faculty_id, faculty_code, faculty_name, dean_name) values
  ('1ab947ed-1cab-4a41-807b-b8c7f2f68c29', 'BIZ', 'NUS Business School', 'NUS'),
  ('9a507eed-0946-4188-9ac2-0c1a17ca2fcc', 'SOC', 'School of Computing', 'NUS'),
  ('f83d64a9-91cb-40f5-a9b7-410736e212c7', 'RMI', 'Risk Management Institute', 'NUS');

insert into student.departments (department_id, department_name) values
  ('18603f1a-766e-4d6b-8ac0-c3e412138578', 'Finance Office'),
  ('3078eda9-f156-4668-9944-375bdb30efb0', 'Faculty Support'),
  ('5db94881-1df4-434e-8de3-69130e4b346f', 'Admissions'),
  ('7984399a-1b70-415e-82b0-3bee7c5c24bf', 'Information Technology'),
  ('90fe27eb-6c61-4ba8-a7a5-8defc69d5626', 'Program Office'),
  ('a339724e-eda0-49a8-869a-83fa19689ea6', 'Student Affairs'),
  ('be2e4662-0bf2-45fb-be36-5d94dffdfed2', 'Alumni Relations'),
  ('e9350d09-ffd6-467f-a998-330e8efd3e31', 'Career Services');

insert into student.courses (course_id, course_code, course_name, course_description, credit_hours, semester_offered) values
  ('0153ee0b-e1fa-4c40-87de-0829f03461bb', 'CS4246', 'Reinforcement Learning and Sequential Decision Making', 'Many tasks performed by AI agents can be formulated as sequential decision making problems. Machine learning in sequential decision making is often done using reinforcement learning. With the prevalence of AI agents, reinforcement learning is becoming increasingly important in many application areas such as large language and other foundation models, robotics, games, and multi-agent systems. This course covers the fundamentals of reinforcement learning, methods for scaling up the learning and sequential decision making processes, as well as selected applications. Topics include model-based and model-free reinforcement learning, exploration, Monte Carlo tree search, function approximation, and concept and techniques from the selected application area.', 4, NULL),
  ('01b7e779-72a6-4ea7-b565-58e79de7fda3', 'IT5001', 'Software Development Fundamentals', 'This course aims to introduce non-computing students to the principles and concepts of software development at an accelerated pace. Students will be introduced to the basics of programming (control flow, code and data abstraction, recursion, types, OO), development methodology (ensuring correctness, testing, debugging), simple data structures and algorithms (lists, maps, sorting), and software engineering principles. Through hands on assignments and projects, students will learn good software development practices (documentation, style) and experience a typical software engineering cycle.', 4, NULL),
  ('029c81fe-1930-408e-b3ac-4a50b221b4ba', 'FE5222', 'Advanced Derivatives Pricing', 'This course will cover the advanced topics related to derivative pricing, including stochastic differential equations, martingale representation theorem and risk-neutral pricing, the change of numeraire argument and pricing of path dependent options (e.g. barrier, lookback, and Asian options), optimal stopping and American options, jump diffusion processes and stochastic volatility for option pricing.', 4, NULL),
  ('044a8d22-1ab3-470c-a31b-9502e3fd3e1e', 'CS5446', 'Reinforcement Learning and Sequential Decision Making', 'Many tasks performed by AI agents can be formulated as sequential decision making problems. Machine learning in sequential decision making is often done using reinforcement learning. With the prevalence of AI agents, reinforcement learning is becoming increasingly important in many application areas such as large language and other foundation models, robotics, games, and multi-agent systems. This course covers the fundamentals of reinforcement learning, methods for scaling up the learning and sequential decision making processes, as well as selected applications. Topics include model-based and model-free reinforcement learning, exploration, Monte Carlo tree search, function approximation, and concept and techniques from the selected application area.', 4, NULL),
  ('04685b7d-7e48-40a5-80c5-0a14350872e4', 'IS4262', 'Digital Product Management', 'This course is designed for students who wants to learn the skills and techniques to manage effectively digital products from cradle to grave. It covers the core aspects of digital product management, from product strategy, planning and development to product launch and support. It will address issues of managing an evolving digital product over its life cycle, and using data from customer insights and competitive analysis for ongoing product iterations. Case studies and hands on experience will be provided. At the end of the course, students will be able to effectively execute the product manager’s role in managing digital products.', 4, NULL),
  ('04b41cd9-a882-48a9-90f2-c1eb380ca815', 'CS4248', 'Introduction to Large Language Models', 'This course deals with computer processing of human languages, including the use of neural networks and deep learning in natural language processing, as embodied in Large Language Models. Topics covered include: n-grams, sequence tagging, word embedding, sequence-to-sequence models and large language models.', 4, NULL),
  ('066508e8-4663-4866-bf51-379ccc339970', 'CS5233', 'Simulation and Modelling Techniques', 'This course aims to provide students with a working knowledge of applying simulation techniques to model, simulate and study complex systems. It covers techniques in simulation model design, model execution, and model analysis. Students will have hands-on experience using a simulation package. The course will also introduce concepts of parallel and distributed simulation, and high level architecture.', 4, NULL),
  ('089439a0-d127-4764-a6ef-636a9edc34d0', 'IT5008', 'Database Design and Programming', 'The aim of this course is to introduce the fundamental concepts and techniques necessary for the understanding and practice of design and implementation of database applications and of the management of data with relational database management systems. The course covers practical and theoretical aspects of design with entity-relationship model, theory of functional dependencies and normalization by decomposition in third and Boyce-Codd normal forms. The course covers practical and theoretical aspects of programming with SQL data definition and manipulation sublanguages as well as relational algebra/calculus.', 4, NULL),
  ('189d04fe-ad50-4a2a-ab98-a4c47b5cc919', 'IS5126', 'Hands-on with Applied Analytics', 'The primary goal of this course is to bridge the significant divide between technical skills and their practical applications in real-world scenarios. Through a hands-on, learning-by-doing approach, students will actively engage in a series of Python-based assignments, culminating in a final semester project. Lectures are designed to cover both practical skills and in-depth technical knowledge, while also discussing various use cases and real-world applications. The course places a strong emphasis on the applied nature of data analytics by covering a broad range of machine learning techniques and methodologies.', 4, NULL),
  ('1d1efd38-bce5-48a2-9058-10cb7c247163', 'IT5006', 'Fundamentals of Data Analytics', 'This graduate-level course provides a comprehensive foundation to the fundamentals of data analytics; namely exploratory data analysis, predictive modeling, and result interpretation. The syllabus emphasizes the translation of real-world scenarios into tractable analytical problems. Students are equipped with a robust toolkit of statistical methods for exploratory analysis. They will delve into the frameworks of both classical and Bayesian learning to tackle analytical challenges. Additionally, the course provides hands-on experience building end-to-end data analytics pipelines using Python. This well-balanced approach integrates technical expertise with business-oriented applications, establishing a strong foundation for pursuing advanced studies in machine learning or business analytics.', 4, NULL),
  ('1f457741-c777-4a9d-8fa9-949ea9c30c4f', 'CS5339', 'Theory and Algorithms for Machine Learning', 'The course aims to provide a broad theoretical understanding of machine learning and how the theory guides the development of algorithms and applications. Topics covered include the approximation capabilities of common function classes used for machine learning, such as decision trees, neural networks, and support vector machines, the sample complexity of learning different function classes and methods of reducing the estimation error such as regularization and model selection, and computational methods used for learning such as convex optimization, greedy methods, and stochastic gradient descent.', 4, NULL),
  ('2b345857-dedb-4088-84b8-70aad49f785d', 'FT5003', 'Blockchain Innovations', 'Blockchain technologies could be the most disruptive FinTech technologies. This course covers the important topics of blockchain innovations. Students will learn the architecture of blockchain, the history and evolution of blockchain applications, and the case studies of state-of-art blockchain applications in the industry.', 4, NULL),
  ('32a621d9-80e5-4d43-82d3-8e642a611420', 'BT4221', 'Advanced Analytics with Big Data Technologies', 'This course introduces students to key concepts in Big Data technologies, covering both foundational and emerging tools and practices. It explores the characteristics and challenges of handling large datasets in different environments. Students will develop practical skills in building and automating data pipelines, managing various forms of data processing, and applying advanced analytical techniques to derive business insights across diverse contexts. The course covers essential topics such as data storage, distributed processing and data streaming. By the end of the course, students will be equipped to apply advanced analytics using Big Data technologies to design and implement effective solutions.', 4, NULL),
  ('344fe126-0c92-4330-9aa9-0404eaebd401', 'CS5260', 'Neural Networks and Deep Learning II', 'This course is a follow-up to CS5242 and covers advanced topics in neural networks and deep learning. This course explores the underlying mechanism of a variety of different types of learning models: unsupervised, semi-supervised, and adversarial learning models, that are not covered in CS5242. Topics may include: generative adversarial networks, adversarial machine learning, zero-shot learning, geometric deep learning, neural architecture search.', 4, NULL),
  ('36144042-f35c-4645-ad6e-b9b67e2f1bf3', 'IS5010', 'AI Ethics and Governance', 'AI introduces new ethical, legal and governance challenges. While organisations depend more on data-driven AI models, the key concerns are how to maintain sufficient control and oversight, ensure data protection and privacy and deploy AI models in ethical and responsible manner. The role of AI ethics and governance is to build trust and confidence in AI. This course imparts students with the frameworks, concepts and techniques to build trustworthy AI solutions.', 4, NULL),
  ('3aef48f6-28a8-4ff9-a323-1e51898ec22a', 'BMF5354', 'Financial Regulation in a Digital Age', 'Finance is a key pillar of modern business organisations. This course examines why and how financial markets and transactions are regulated, with a focus on corporate fundraising and how the regulatory reforms following the 2008-9 Global Financial Crisis are changing the financial landscape. The course also introduces how technological developments (e.g. blockchains, cloud computing, artificial intelligence) are rapidly transforming finance, and highlights regulatory issues that need to be addressed to leverage the potential of Fintech.', 4, NULL),
  ('3d0a68c9-eed8-4bb0-9ac2-68c76f2b8174', 'CS6283', 'Topics in Computer Science: Robot Learning in the Era of Foundation Models', 'This advanced course explores modern machine-learning algorithms for autonomous robots as embodied intelligent agents, examining how embodied AI differs from internet AI in perceiving raw sensory data, making decisions, and adapting to the physical world. It bridges classical techniques with recent advances in large-scale models, starting from the fundamentals of robotic manipulation, imitation learning, reinforcement learning, and policy optimization, and progressing to Vision-Language-Action (VLA) models and foundation models for robotics. Through debating cutting-edge papers and completing a hands-on project, students will learn to formulate problems, design algorithms, validate ideas experimentally, and engage with the research process.', 4, NULL),
  ('3dfc16dc-58d3-40c2-806b-a564b471f044', 'FE5108', 'Portfolio Theory And Investments', 'Portfolio Optimisation Theory. The first half of the course (50%) is devoted to topics including decision making under uncertainty, Markowitz mean-variance portfolio, capital asset pricing model (CAPM), multifactor pricing models, and dynamic portfolio optimization (intertemporal portfolio choice and asset pricing). The second half of the course (50%) covers how these notions are applied in investment management practice.', 4, NULL),
  ('420fea4a-e37c-4a26-ba15-dbf8198c51c2', 'BT5126', 'Hands-on with Business Analytics', 'Business analytics is the use of data to support business decisions. This course draws a unique blend of business strategies, theory and a practical hands-on experience with the tools and techniques to support the strategies. The course will take students through all the stages of an analytic project from design, data collection, execution and presentation. Through a learning-by-doing approach, students will engage in business cases, guided projects and a project of their own design. Lectures will cover a breadth of technical tools and statistical methods through the data pipeline in an organization. The course will especially emphasize on techniques for causal analysis and econometric identification.', 4, NULL),
  ('481c85ab-36d0-43c0-b639-ebf8b6a7ec6e', 'IS5006', 'Human-Centred Intelligent Systems', 'This course covers intelligent systems solutioning with human-centred machine learning frameworks and human interactions with AI technologies. Intelligent systems have the capacity to gather and analyse data, learn from experience, and adapt according to external stimuli. The course applies human-centred machine learning frameworks to develop novel solutions that synergise human needs with AI capabilities. Students will get hands-on experience in prototyping solutions with a human-centred AI approach. The course will also cover how human-centred AI can be used to solve existing business needs, shape business strategy or create new business opportunities.', 4, NULL),
  ('49ceef18-e0f4-491b-bdf6-79d9ec567ffa', 'FT5014', 'AI Risk in the Financial Sector', 'Financial institutions worldwide increasingly deploy AI, agentic and generative AI to drive innovation in areas like fraud detection, customer personalisation, and automated trading, yet these technologies introduce unprecedented risks such as model biases, adversarial attacks, and supply chain vulnerabilities that have led to multimillion-dollar incidents. This course equips students with essential skills to navigate this high-stakes landscape, transforming potential threats into opportunities for resilient, trustworthy AI adoption that aligns with regulatory demands from bodies like Singapore MAS, US FFIEC, and the European Union AI Act. For students, it offers a competitive edge in fintech careers by blending practical risk analysis with real-world case studies, latest institutional and regulatory developments in the high-stake accelerated adoption of AI in the global financial sector, addressing the urgent industry need for professionals who can balance innovation with trust.', 4, NULL),
  ('4b19abc5-a143-430e-a961-083974d30a0a', 'BMF5353', 'Applied Investment Strategies', 'This course comprises the application of various active investment strategies with a concentration on developing an investment program which includes alternative asset classes. Topics will include how to research, evaluate and select different alpha generating investments into a practical ready to use investment program. Different manager styles will be discussed and will cover both quantitative and qualitative methods to assess the strengths and weaknesses of various investment managers and styles. Alternative asset classes studied will include hedge funds, real estate funds, infrastructure investments, private equity, private debt, managed futures and commodities. We will also discuss risk management and control issues in investment programs. The course will explore the impact of regulatory changes and emerging market variables on the performance of investment programs.', 4, NULL),
  ('4bbb24c8-1d5e-4463-b710-53f7c06ce12e', 'IS5152', 'Data-Driven Decision Making', 'Data driven decision making improves productivity and profitability of businesses. This course teaches students decision making techniques based on data analysis. Various Machine Learning (ML) techniques for data analysis will be presented. The course also discusses aspects related to building an effective model for decision making such as: (i) methods for data preparation such as feature selection, data reduction and sample selection, (ii) metrics for determining a good model, (iii) visualization of model performance, (iv) overfitting and its avoidance. Examples of practical business decision making problems will be used to illustrate the merits of the ML techniques presented.', 4, NULL),
  ('4d30a936-4c42-4f6f-80d4-6c62a5933f9c', 'FT5007', 'FinTech Capstone Project', 'Capstone project course spans over two semesters and is organised into two components. The first semester will comprise of a series of seminar-lectures that would help prepare students for conducting a literature review, working on pilot projects, and facilitating industry attachment for a summer internship. Starting in the first semester, students are required to work on a FinTech project. The project could be academic research, translational research, or software development.', 12, NULL),
  ('5c7338ca-a012-4678-a7e7-e455bdc05c56', 'IS4301', 'Agile IT with DevOps', 'Acceleration of the pace of digital transformation and adaption to business changes have caused IT organizations to integrate Agile methods and DevOps with traditional IT development and operations. This course introduces students with essential concepts of Agile IT and DevOps for participation in agile IT business transformations. Topics covered shall include waterfall vs. agile, integrated agile methods (Xtreme Programming, Scrum), DevOps, hybrid-IT, Platform as a service, monolithic vs. microservice architecture, containerization, toolchains, open innovations and case studies. Banking industry services will be used to enable students to practise concepts taught in this course.', 4, NULL),
  ('641717a3-d1af-433f-adcf-964aa75e72c8', 'CS5340', 'Uncertainty Modelling in AI', 'The course covers modelling methods that are suitable for reasoning with uncertainty. The main focus will be on probabilistic models including Bayesian networks and Markov networks. Topics include representing conditional independence, building graphical models, inference using graphical models and learning from data. Selected applications in various domains such as speech, vision, natural language processing, medical informatics, bioinformatics, data mining and others will be discussed.', 4, NULL),
  ('69c64c7b-3a3e-4f1c-ae37-65cf66ee16de', 'FT5005', 'Machine Learning for Finance', 'This course covers foundation knowledge in machine learning and data mining for solving practical analytics problems or building AI applications at FinTech firms. Some topics covered including supervised learning models, time series forecasting methods, basics of natural language processing, and unsupervised learning.', 4, NULL),
  ('6a31dd61-3ab6-44a7-b865-b1da1b8ef26f', 'FT5010', 'Algorithmic Trading Systems Design and Deployment', 'The course teaches students financial market fundamentals and best practices in systematic trading, covering the distinction between discretionary and systematic methods. It emphasizes designing and developing rule-based trading strategies and systems, utilizing financial trading and app development concepts. It focuses on best practices for backtesting and hypothesis testing for different trading strategies derived from technical analysis, fundamental analysis, and machine learning. The course also addresses investor biases and ways to overcome them through data-driven decision-making and risk management.', 4, NULL),
  ('6ac79d0e-87b7-4f49-b190-046f1303a48a', 'IS4234', 'Governance, Regulation, and Compliance Technology', 'Organizations today need to be aware of and ensure that they comply with all relevant laws and regulations. At the same time, regulators are faced with challenges of enforcing compliance. Digital technology can be used to facilitate both organizational compliance and regulatory enforcement of compliance. Additionally, increasing use of IT requires governance and regulation of technology itself. This course allows students to gain an understanding of how IT can be governed and regulated, as well as how it can be applied for compliance and regulation, for example in the financial sector.', 4, NULL),
  ('7134a9c4-eaa2-4712-80f9-208ae0db6114', 'CS5231', 'Systems Security', 'This course introduces fundamental notions and requirements in computer system security and the mechanisms that provide security in various systems and applications. It aims to teach students the security perspective of popular computer systems, such as desktop systems, mobile systems, and web-based systems. Its topics include software security, operating system security, mobile security, web security, trusted platforms, and auditing and forensic analysis.', 4, NULL),
  ('72f07a48-26cc-4ee7-b294-7596c3e2245a', 'IT5005', 'Artificial Intelligence', 'The study of artificial intelligence, or AI, aims to make machines achieve human-level intelligence. This course provides a comprehensive introduction to the fundamental components of AI, including how problem-solving, knowledge representation and reasoning, planning and decision making, and learning. The course prepares students without any AI background to pursue advanced courses in AI.', 4, NULL),
  ('7736a08d-0e38-4e98-a79c-07bb772026e3', 'BT4013', 'Analytics for Capital Market Trading and Investment', 'This course broadly covers quantitative trading, focusing on strategies built through time-series analysis. Techniques for identifying trading opportunities by sifting through historical data will be explored. The course also addresses the quantification of risk associated with potential trading decisions.', 4, NULL),
  ('785a4a2e-0bcd-482c-b2d9-c16821589486', 'CS4225', 'Big Data Systems for Data Science', 'Data science incorporates varying elements and builds on techniques and theories from many fields, including statistics, data engineering, data mining, visualization, data warehousing, and high-performance computing systems with the goal of extracting meaning from big data and creating data products. Data science utilizes advanced computing systems such as Apache Hadoop and Spark to address big data challenges. In this course, students will learn various computing systems and optimization techniques that are used in data science with emphasis on the system building and algorithmic optimizations of these techniques.', 4, NULL),
  ('7b22c97c-ccc3-42cb-b62c-4ab2c1064a74', 'FT5013', 'Digital Asset Innovations in Finance', 'This course offers an in-depth exploration of the technological innovations driving the emergence and growth of digital assets in finance. Students will delve into the foundational concepts of digital assets, understand the mechanics of decentralized finance (DeFi), and examine the cutting-edge technologies shaping the future of the financial industry. The course is structured to build knowledge progressively, starting from basic principles and advancing to complex applications and future trends.', 4, NULL),
  ('7d6bfa93-abd2-4d68-96c2-e0a6694c38fb', 'IT5003', 'Data Structures and Algorithms', 'This course introduces non-computing students to efficient computational problem solving in an accelerated pace. Students will learn to formulate a computational problem, identify the data required and come up with appropriate data structures to represent them, and apply known strategies to design an algorithm to solve the problem. Students will also learn to quantify the space and time complexity of an algorithm, prove the correctness of an algorithm, and the limits of computation. Topics include common data structures and their algorithms (lists, hash tables, heap, trees, graphs), algorithmic problem solving paradigms (greedy, divide and conquer, dynamic programming), and NP-completeness.', 4, NULL),
  ('803a60c0-9f8c-475d-b75e-b2c1100a7eb4', 'FT5004', 'Programming for Blockchain Applications', 'This course provides an overview of the essential concepts for blockchain application development. Students will be able to understand how blockchain applications function and the differences compared to traditional applications. Additionally, they will gain knowledge of the standards, key libraries, and services required for blockchain application development and be able to utilize them effectively.', 4, NULL),
  ('8562bf9b-54d1-4f06-b9e8-51eb3a238da7', 'CS5242', 'Neural Networks and Deep Learning', 'This course provides students with the knowledge of deep neural network and enables them to apply deep learning methods effectively on real world problems. The course emphasizes on the understanding of the principles of neural networks and deep learning; practical guidelines and techniques for deep learning; and their applications. Through assignments and projects, students will design, develop, and evaluate deep learning-based solutions to practical problems, such as those in the areas of computer vision, bioinformatics, fintech, cybersecurity, and games.', 4, NULL),
  ('884ae939-d4ae-4671-9b0f-3b7656efbdfd', 'FT5012', 'Digital Trust in Banking and Finance', 'Globally, the banking and finance sector has witnessed many rapid changes in recent years. These include advancements in digital technologies, evolving practices in delivering digital financial services, shifts in the security threat and risk landscape, heightened connectivity with ecosystem partners, and increasing expectations from government and financial regulators. Consequently, it is of utmost importance that financial institutions and other critical sectors of the economy implement robust enterprise-level risk governance and strong risk management practices, safeguarding critical services against cybercriminals and digital fraud. Such a multipronged strategy will ensure that digital financial services remain resilient and provide adequate protection for personal information and privacy. This course will prepare students to tackle these global challenges effectively.', 4, NULL),
  ('8b1aec50-2ea3-4737-8b36-b63d702f5f01', 'FT5011', 'Deep Learning for Finance', 'This course will introduce the foundational concepts and applications of major deep learning algorithms. This course aims to bridge the gap between the rapidly evolving world of deep learning technologies and the unique challenges presented by the financial industry. Through a combination of theoretical lessons, practical case studies, hands-on exercises, and discussions, students will explore the potential, limitations, and implications of employing deep learning solutions in various financial scenarios. By the end of this course, participants will have hands-on experience in designing, training, and implementing deep learning models for financial applications.', 4, NULL),
  ('8ddcf363-6352-439c-bae0-38cc4aa523e6', 'BMF5342', 'Financial Technology and Analytics', 'This course covers innovations and analytical tools in finance that solve practical problems. The objective is to leverage technology and analytics to drive financial decision-making (e.g., evaluating investment opportunities and designing investment strategies) and generate business value (e.g., improving financial operations and creating new businesses). The topics cover platform economics, market efficiency, behavioral finance, event studies, Monte Carlo simulation, real options, digital transformation, artificial intelligence (AI), generative AI, digital payments, cryptography and cybersecurity, and blockchain.', 4, NULL),
  ('94c121fe-7900-495b-a0a6-145074ad8691', 'IS5008', 'Technology Risk & Cyber Resilience', 'Enterprise today needs to be able to identify and assess the impact of the technology risk on the resilience of the enterprise to allow them to respond to these issues in a cost-efficient, effective and sustainable way. The course consists of three broad aspects, namely, (a) identification and understanding of the drivers of technology risk & resilience, (b) the foundational elements of technology risk & resilience framework, and (c) how enterprises implement technology risk and cyber resilience framework in the real world.', 4, NULL),
  ('951cc694-e258-41ea-99d2-08a1b401505a', 'BMF5355', 'Financial Systems and Technologies', 'The objective of this course is to introduce students to the systems and technologies used by financial institutions and markets. It will also explore future trends, opportunities, and threats that these systems and technologies provide.', 4, NULL),
  ('9754ebb5-af62-419e-bac4-bfb44ab82487', 'BMF5358', 'Fintech Venture Creation', 'This course introduces problem identification, ideation, opportunity evaluation, product design, and prototyping in digital and decentralized finance. Through a review of various business models and their enabling technologies, such as distributed ledgers, open APIs, and AI, you will gain insights into the transformative power of financial technology within the financial services industry. Leveraging the insights from your primary market research and the capabilities of generative AI, you will learn to identify existing gaps in traditional finance, conceive innovative business ideas, develop a solid proof of concept, design an effective business model, construct a concrete financing plan, and create a comprehensive business plan.', 4, NULL),
  ('9a130c8e-7d60-4972-a2b9-16811bb17253', 'IS4246', 'Smart Systems and AI Governance', 'This course is designed for students who want to design and manage smart systems that use Artificial Intelligence (AI) and Machine Learning (ML) to improve product and service offerings in enterprises and businesses across different industries. It covers the use of an AI governance framework to ensure the design and deployment of intelligent systems protect individual and organisational interests such as transparency, safety, well-being, fairness, privacy and security. Application areas include AI/ML in smart hospitals, autonomous vehicles, intelligent energy management with edge AI for business and homes, and many more.', 4, NULL),
  ('9ebf8742-2601-4e39-828d-4c02923ca567', 'CS5224', 'Cloud Computing', 'This course aims to provide an overview of the design, management and application of cloud computing. The topics include virtualization, cloud computing environments, cloud application deployment, cloud use cases, data center architectures and technologies, cloud services fulfillment and assurance, orchestration and automation of cloud resources, cloud capacity management, cloud economics, case studies.', 4, NULL),
  ('a7f35bc7-8308-4ed5-9175-3ef418e00540', 'BT4016', 'Risk Analytics for Financial Services', 'This course exposes students to the fundamentals of risk analytics in the financial services sector. Students will be taught on the fundamentals of financial services and financial risks. They will also learn about interest rate risk analytics and credit risk analytics.', 4, NULL),
  ('aa9b45b1-e526-4cd4-91e5-24da8858ffd5', 'AI5205', 'Ethics, Governance, and Compliance in AI and Emerging Technologies', 'This course addresses the crucial need for ethical leadership and compliance in the rapidly evolving domains of AI and Blockchain technology. This course explores foundational ethical principles, governance frameworks, and regulatory considerations essential for executives navigating these technologies. Key topics include ethical AI use, blockchain transparency, data privacy, regulatory compliance, and the societal impacts of technological advancements. Through case studies and industry examples, leaders will learn to implement responsible practices that align with global standards and foster trust and integrity in AI and blockchain initiatives.', 4, NULL),
  ('ab6049fc-b642-4837-b3f1-af5b270e13a3', 'CS5321', 'Network Security', 'The objective of this course is to introduce students to the various issues that arise in securing the networks, and study the state-of-the-art techniques for addressing these challenges. A number of most damaging attacks on computer systems involve the exploitation of network infrastructure. This course provides an in-depth study of network attack techniques and methods to defend against them. Topics include basic concepts in network security; firewalls and virtual private networks; network intrusion detection; denial of service (DoS); traffic analysis; secure routing protocols; protocol scrubbing; and advanced topics such as wireless network security.', 4, NULL),
  ('abb22704-f304-4c68-b0a4-c97f954367ba', 'CS5425', 'Big Data Systems for Data Science', 'Data science incorporates varying elements and builds on techniques and theories from many fields, including statistics, data engineering, data mining, visualization, data warehousing, and high-performance computing systems with the goal of extracting meaning from big data and creating data products. Data science needs advanced computing systems such as Apache Hadoop and Spark to address big data challenges. In this course, students will learn various computing systems and optimization techniques that are used in data science with emphasis on the system building and algorithmic optimizations of these techniques.', 4, NULL),
  ('af38b641-6906-478a-b5c0-a0711bf34136', 'CS5246', 'Text Mining', 'Text mining concerns the processing of unstructured natural language text to mine information and knowledge. It is distinguished from data mining in its focus on unstructured text rather than structured data present in traditional databases. Topics include text classification, text clustering, sentiment analysis, text summarization, information extraction (named entity recognition, relation and event extraction), and question answering. The course will emphasize the use of machine learning approaches to text mining.', 4, NULL),
  ('afcf443e-27db-4650-984b-fd102d246155', 'BMD5302', 'Financial Modelling for FinTech Professionals', 'This course introduces Finance models used in corporate finance, portfolio management, derivatives and bonds. It takes an applied approach by implementing through Excel, VBA and Python.', 4, NULL),
  ('b1698209-f018-4335-9f9e-bf8d2b2526b9', 'IS3251', 'Principles of Technology Entrepreneurship', 'The course introduces students to the concepts and principles of technology entrepreneurship. Students will learn about the current developments in entrepreneurship, worldwide and in Singapore and be taught to use a variety of tools, techniques and frameworks for the development and analysis of entrepreneurial businesses. Students taking the course should have an interest in entrepreneurship and a desire to be an entrepreneur at some stage in their lives.', 4, NULL),
  ('b3f9affc-7281-458a-8dbc-a0893d75fb5b', 'FT5002', 'Digital and AI Transformation in Finance', 'This course equips students to lead digital and AI transformation in banking and finance enterprises by providing an end-to-end framework for staging and executing digital and AI transformation programs. It covers change management and strategic transformation, the modernisation of legacy core banking and financial systems, and building “digital-to-the-core” capabilities through culture, operating model, architecture and human capital. Students will learn how to transition financial institutions into a data- and AI-driven operating environment, including platform and infrastructure considerations, governance, and regulatory considerations.', 4, NULL),
  ('b48a738b-0475-42cf-b186-da4a12f635bb', 'FE5103', 'Equity Products and Exotics', 'This course is a core course for students of MSc in Financial Engineering. The topics include: Covered warrants, equity warrants and options, subscription rights, stock index futures and options, and other equity derivatives. Issues of pricing and hedging. Institutional constraints. Portfolio management and other investment strategies. Path-dependent options such as Asian options, barrier options, lookback options, and forward-start options. Spread options, rainbow options, quantos, exchange options, basket options, as-you-like options, power options, digital options, and others. Pricing techniques and risk management purposes.', 4, NULL),
  ('b5ccd84c-fef6-4a9a-9e07-8cb988d9bb8a', 'IT5001X', 'Software Development Fundamentals', 'This course aims to introduce non-computing students to programming principles and their application in software development. Students will be introduced to the basics of programming (control flow, data and function abstraction, types, OO), simple data structures and algorithms (lists, maps, sorting), and development methodology (testing, debugging). Through hands on assignments, students will learn good software development practices (documentation, style) and experience building practical applications. This course is appropriate for students in programmes with non-CS focus.', 4, NULL),
  ('b67dc8a7-8715-4613-a051-591483d92943', 'CS4221', 'Database Applications Design and Tuning', 'This course addresses the design and performance tuning of database applications. The syllabus focusses on relational database applications implemented with relational database management systems. Topics covered include normalisation theory (functional, multi-valued and join dependency, normal forms, decomposition and synthesis methods), entity relationship approach and SQL tuning (performance evaluation, execution plan verification, indexing, de-normalization, code level and transactions tuning). The syllabus optionally includes selected topics in the technologies, design and performance tuning of non-relational database applications (for instance, network and hierarchical models and nested relational model for an historical perspective, as well as XML and NoSQL systems for a modern perspective).', 4, NULL),
  ('bafe725e-87e3-4e6d-9e5a-4f61aed5d8a5', 'IS4226', 'Systematic Trading Strategies and Systems', 'The course aims to provide students with the fundamentals of financial market and systematic trading. It covers the difference between discretionary trading and systematic trading, as well as the best practices in developing backtesting systems. The course will emphasise the design and development of trading strategies and systems with the help of technical analysis and machine learning. It will focus on rule-based systematic trading, both manual and through algorithms. It will also cover investor biases and how to overcome them through data and systems to make better trading decisions and have appropriate risk management.', 4, NULL),
  ('bd86d393-6062-4d30-ad29-f0e3cedd43bd', 'CS5228', 'Knowledge Discovery and Data Mining', 'This course introduces fundamental principles behind data mining and efficient techniques for mining large databases. It provides an overview of the algorithmic aspect of data mining: its efficiency (high-dimensional database indexing, OLAP, data reduction, compression techniques) and effectiveness (machine learning involving greedy search, branch and bound, stochastic search, parameter optimisation). Efficient techniques covered include association rules mining (Apriori algorithm, correlation search, constrained association rule discovery), classifier induction (decision trees, RainForest, SLIQ; Support vector machine; Naive Bayesian; classification based on association / visualisation), cluster analysis (k-means, k-mediods, DBSCAN, OPTICS, DENCLUE, STING, CLUSEQ, ROCK etc), and outliers/deviants detection (LOF, Distance-based outlier etc).', 4, NULL),
  ('c13f592b-2c2f-499c-bf3f-73e0ca335bb8', 'FT5009', 'Contemporary Topics in Financial Data Analytics', 'The objective of this course is to provide students with an overview of recent advances in financial data analytics. In addition, the lecturer may provide an in-depth discussion of selected important topics in financial data analytics that is the focus of industry-oriented research at financial institutions or start-ups. From this course, students will learn advanced data mining algorithms, financial statistical models, fintech programming knowledge, and business cases or academic papers on modern financial applications.', 4, NULL),
  ('c4bee792-ac43-4251-969b-6b6386afa5fb', 'CS5331', 'Web Security', 'This course aims to prepare graduate students for understanding the security of the latest web platform and its interplay with operating systems and the cloud infrastructure. The topics covered include the design of web browsers and web applications, vulnerabilities in web applications and web browsers, design of web scanners, authentication in web-based platforms, security policies and enforcement mechanisms. This course also covers security topics on the interface between the web platform and the backend systems, such as the underlying database systems and cloud infrastructure.', 4, NULL),
  ('cdc5d3c2-c0e8-4f5a-a7a0-0153dc08e39a', 'FT5001', 'FinTech Innovations: A Strategic Landscape', 'The objective of this course is to provide a technological overview of the eco-system of FinTech innovations for consumers. Particularly, this course will cover important business models and innovations in payment solutions, crowd-funding platforms, investment and robo-advisors, and other important FinTech innovations that affect the personal finance of individual consumers.', 4, NULL),
  ('ce9cde39-47d2-4eb3-b1ff-02fa78c92c53', 'CS4239', 'Software Security', 'Software engineering processes need to include security considerations in the modern world. This course familiarizes students to security issues in different stages of the software life-cycle. At the end of the course, the students are expected to understand secure programming practices, be able to analyse and check for impact of malicious inputs in programs, and employ specific testing techniques which can help detect software vulnerabilities.', 4, NULL),
  ('cf1e5037-b7b0-4e69-b355-74d2b8e802b5', 'IS5116', 'Digital Entrepreneurship', 'The key concepts of entrepreneurship are first covered, giving students the necessary background knowledge and an opportunity to develop a tech startup venture as a team project. Following that, sessions are set aside for students to learn a wide range of issues about entrepreneurship by asking questions and hearing first hand from people who are active in the startup eco-system as entrepreneurs or investors. The student would understand what is involved in building a high tech start-up company and know how to develop an entrepreneurial venture. He would also be familiar with the entrepreneurship eco-system in Singapore.', 4, NULL),
  ('d54ccb9f-1100-45b8-89c6-2287b1c78f04', 'CS5562', 'Trustworthy Machine Learning', 'This course covers theoretical foundations of trustworthy machine learning. It covers tools for the analysis of privacy, robustness, and fairness in machine learning using techniques from statistics, probability, and machine learning. Some questions considered include: Can we trust machine learning frameworks to access sensitive personal data? Can we trust algorithms to learn robust decision rules in the presence of adversarial and noisy data? Can we build algorithms that provide fair predictions and avoid discrimination? Can we make machine learning models more verifiable, interpretable, ethical, and accountable? The course provides an algorithmic approach towards defining and achieving trustworthy machine learning.', 4, NULL),
  ('df6254a1-231a-4227-8cab-d1d3e9d0eed3', 'IS5009', 'Topics in Financial Technology Solutions', 'Focusing on the financial sector and with the technological solutioning in mind, students can look forward to learning contemporary issues in the financial technology space. The course will investigate the integration of financial domain knowhow and advanced technologies, such as the algorithmic trading for the financial market. Students are advised to look into content detail for specific offering during the year.', 4, NULL),
  ('e298be5e-fc53-499d-8fba-f1a819f6d92f', 'CS5344', 'Big-Data Analytics Technology', 'This course analysis of data which can not fit in main memory and application of such analysis to web applications. The topics covered include: map-reduce as a tool for creating parallel algorithms that operate on very large amount of data, similarity search, data-streaming processing, search engine technology, clustering of very large, high-dimensional datasets.', 4, NULL),
  ('e96f8b34-5158-415b-bfe4-46cb3bd629db', 'IS4261', 'Designing AI-driven Business Innovations', 'Information technology has fundamentally transformed how businesses are innovating with new service and product offerings in an accelerated digital economy. In this new era of digital transformation, data and Artificial Intelligence (AI) are increasingly being harnessed to develop an in-depth understanding of customers thus enabling more effective engagement. Beyond customer engagement, businesses are also leveraging data and AI to automate business processes and digitise risk management and IT governance to improve resiliency. This course teaches students on how to design data/AI-driven business innovations in digital transformation of businesses.', 4, NULL),
  ('f19a2eaf-a192-473e-bf3a-80b395af6ea6', 'IT5004', 'Enterprise Systems Architecture Fundamentals', 'This course aims to equip non-computing students with fundamental knowledge in architecting and designing modern Enterprise Systems in organisations that can be reasonably complex, scalable, distributed, component-based and mission critical. Students will develop an understanding of high-level concepts such as enterprise architecture and software architecture. They will then move on to acquire fundamental systems analysis and design techniques such as object-oriented requirements analysis and design using the Unified Modelling Language.', 4, NULL),
  ('f6fda3bb-73de-4adf-8878-9414232e7a49', 'BMF5346', 'Venture Capital and Private Equity', 'This course covers major private equity investment types including venture capital, growth capital and buyouts. The course format will include lectures, interactive discussions, case studies and hands-on simulation. Topics will cover the entire private equity investment cycle from fund raising, structuring to deal screening, valuation, investment negotiations to post-investment value add and exits. An underlying theme of the course is to evaluate to what extent venture capital and private equity markets can create value and wealth, generate social return and promote economic growth.', 4, NULL),
  ('faa6f208-e798-43f9-9bc3-76d80f371299', 'CS5439', 'Software Security', 'Software engineering processes need to include security considerations in the modern world. This course familiarizes students to security issues in different stages of the software life-cycle. At the end of the course, the students are expected to understand secure programming practices, be able to analyse and check for impact of malicious inputs in programs, and employ specific testing techniques which can help detect software vulnerabilities.', 4, NULL),
  ('fd16ae8e-3345-41b8-8d24-2caac177203e', 'CS5421', 'Database Applications Design and Tuning', 'This course addresses the design and performance tuning of database applications. The syllabus focuses on relational database applications implemented with relational database management systems. Topics covered include normalisation theory (functional, multi-valued and join dependency, normal forms, decomposition and synthesis methods), entity relationship approach and SQL tuning (performance evaluation, execution plan verification, indexing, de-normalization, code level and transactions tuning). The syllabus optionally includes selected topics in the technologies, design and performance tuning of nonrelational database applications (for instance, network and hierarchical models and nested relational model for an historical perspective, as well as XML and NoSQL systems for a modern perspective).', 4, NULL),
  ('fd9dcd6e-e90f-4588-9e94-a688dc0ec078', 'BMD5301', 'Introduction to Finance for FinTech Professionals', 'This course aims to provide students with the foundation to understand the key concepts and tools used in Finance, which are necessary for managers and analysts to make sound financial decisions. Topics covered include discounted cash flow models, risk and return, capital budgeting, valuation of stocks and other financial securities, as well as an overview of financial markets and financial institutions.', 4, NULL);

insert into student.academic_departments (department_id, department_code, department_name, faculty_id) values
  ('6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'CS', 'Computer Science', '9a507eed-0946-4188-9ac2-0c1a17ca2fcc'),
  ('6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'BIZ', 'BIZ Dean''s Office', '1ab947ed-1cab-4a41-807b-b8c7f2f68c29'),
  ('b4febcd3-7b79-4508-a754-867cd8f85a65', 'RMI', 'Risk Management Institute', 'f83d64a9-91cb-40f5-a9b7-410736e212c7'),
  ('d28ab726-a0c2-4eff-853e-2fbc036968b0', 'ISA', 'Information Systems and Analytics', '9a507eed-0946-4188-9ac2-0c1a17ca2fcc');

insert into student.programs (program_id, faculty_id, program_code, program_name, program_level, duration_years, total_credit_required, description, career_outcomes, tuition_fee, status) values
  ('0f10fcf0-90f9-4ace-9d99-c665a796befb', '9a507eed-0946-4188-9ac2-0c1a17ca2fcc', 'DFT', 'Master of Digital Financial Technology', 'Master', 2, 52, 'FinTech is designed to help students build a strong foundation in computing and finance, and features a range of elective courses organised along three tracks: Computing Technologies, Financial Data Analytics and Intelligence, and Digital Financial Transactions and Risk Management.', 'AI software developers, data scientists, FinTech security specialists, financial quantitative analysts and other similar professions in financial institutions or FinTech firms', 74120.00, 'Active');

insert into student.program_departments (program_department_id, program_id, department_id, role) values
  ('3e66ed9d-20d9-4c53-9603-b39655f9efa8', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('73a427ad-7e6b-4e01-b354-4d13fe523a73', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('c361e4c7-ca87-4d33-a2e5-9bcce261f158', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'b4febcd3-7b79-4508-a754-867cd8f85a65', 'Contributing'),
  ('de5a42c7-4d5c-49d0-ad88-305d662f1cd5', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead');

insert into student.program_courses (program_course_id, program_id, course_id, course_type) values
  ('00fa4d9c-da88-445d-8074-eed592985b78', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'ce9cde39-47d2-4eb3-b1ff-02fa78c92c53', NULL),
  ('02826ae1-d6b9-4bbf-894a-4fd257f45b8a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'bd86d393-6062-4d30-ad29-f0e3cedd43bd', NULL),
  ('02a5a9a0-6b3c-4cc5-be9a-46b0d942fe23', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'ab6049fc-b642-4837-b3f1-af5b270e13a3', 'Vertical #1. Computing Technologies'),
  ('04ad752a-f391-4609-9b9a-51a235bb80a1', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '1f457741-c777-4a9d-8fa9-949ea9c30c4f', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('076a91cb-3c94-4a8e-b3db-16e60a088f3b', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'e298be5e-fc53-499d-8fba-f1a819f6d92f', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('08781588-79e8-422f-8699-f54ef77f912c', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '420fea4a-e37c-4a26-ba15-dbf8198c51c2', NULL),
  ('178e706b-6e87-42ee-b235-8700eb5cea9e', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '7b22c97c-ccc3-42cb-b62c-4ab2c1064a74', 'Core'),
  ('23cc9829-27ff-457a-8cae-18acdacec16e', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '8b1aec50-2ea3-4737-8b36-b63d702f5f01', 'Core'),
  ('309dfc5f-ed51-4819-94f2-4c4fc3d5765a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '32a621d9-80e5-4d43-82d3-8e642a611420', NULL),
  ('34901c5f-a75d-4bc6-a2a7-1465571cb034', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '4bbb24c8-1d5e-4463-b710-53f7c06ce12e', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('3ec74283-a3e3-4e7b-bd23-629d959893c6', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'cf1e5037-b7b0-4e69-b355-74d2b8e802b5', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('42fe613c-fdd5-44d3-a018-5e74152c81c4', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'cdc5d3c2-c0e8-4f5a-a7a0-0153dc08e39a', 'Core'),
  ('4a2e0b28-49ca-477d-b716-f4477565a9df', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '6a31dd61-3ab6-44a7-b865-b1da1b8ef26f', 'Core'),
  ('4b345276-6a12-4683-8428-c25807cbd811', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '3dfc16dc-58d3-40c2-806b-a564b471f044', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('4fa8ffc8-0a75-4d95-8c26-4ae272ad9773', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '04b41cd9-a882-48a9-90f2-c1eb380ca815', NULL),
  ('505b6964-644f-475a-877b-5cb5c713bb3d', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '36144042-f35c-4645-ad6e-b9b67e2f1bf3', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('54bc2f35-4e52-46fe-9e86-1efed3d2b3d7', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '6ac79d0e-87b7-4f49-b190-046f1303a48a', NULL),
  ('55873cc9-7ff8-4f20-a4e4-961c194133ff', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '69c64c7b-3a3e-4f1c-ae37-65cf66ee16de', 'Core'),
  ('56790ea5-2bc6-4329-93dd-73d8457ead15', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'e96f8b34-5158-415b-bfe4-46cb3bd629db', 'Vertical #1. Computing Technologies'),
  ('5c1777e6-ad0c-4e46-bcf7-80f1267de1ca', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '951cc694-e258-41ea-99d2-08a1b401505a', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('5e5fe4ef-bf8a-4d5d-9c4c-a9c114f08500', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '4b19abc5-a143-430e-a961-083974d30a0a', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('5fa66b9e-8fa0-4564-b488-c3354021a26c', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '803a60c0-9f8c-475d-b75e-b2c1100a7eb4', 'Core'),
  ('62e0c39a-7c42-4977-80b7-5e2c3b30e875', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'faa6f208-e798-43f9-9bc3-76d80f371299', 'Vertical #1. Computing Technologies'),
  ('63e5b53b-b994-4df4-849e-fe5a690544c6', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'b67dc8a7-8715-4613-a051-591483d92943', NULL),
  ('659aaf95-eb96-447c-90aa-527c75b6592a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '7134a9c4-eaa2-4712-80f9-208ae0db6114', 'Vertical #1. Computing Technologies'),
  ('66eb1bdc-7a5f-4cf9-b9ea-49c42b43872a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '0153ee0b-e1fa-4c40-87de-0829f03461bb', NULL),
  ('69d7bcf9-97d5-4170-a48a-68d71db78e5a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '94c121fe-7900-495b-a0a6-145074ad8691', 'Vertical #1. Computing Technologies'),
  ('6cd039a8-f596-429c-97e3-1419125d74ff', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'af38b641-6906-478a-b5c0-a0711bf34136', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('6d9eb46f-220a-4f5c-8f94-584fe1aca857', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'c13f592b-2c2f-499c-bf3f-73e0ca335bb8', 'Core'),
  ('6eedecfe-bac1-402e-97ef-d5f4f0574841', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '3aef48f6-28a8-4ff9-a323-1e51898ec22a', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('7325b77e-e6d4-47f7-a742-4e053076e89d', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '4d30a936-4c42-4f6f-80d4-6c62a5933f9c', 'Capstone Project'),
  ('75f10a0f-a0f3-4f6d-8957-64456ea8d27f', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'a7f35bc7-8308-4ed5-9175-3ef418e00540', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('763456cf-d74f-46ad-95c3-2dea19ae324f', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '04685b7d-7e48-40a5-80c5-0a14350872e4', 'Vertical #1. Computing Technologies'),
  ('7c21e48e-587f-42f1-b961-07a2a5b28df0', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'c4bee792-ac43-4251-969b-6b6386afa5fb', 'Vertical #1. Computing Technologies'),
  ('80b9ddbe-2ffc-45ed-bbf6-4bf374ac1e5b', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '7d6bfa93-abd2-4d68-96c2-e0a6694c38fb', 'Core'),
  ('820398ce-5928-4518-aaa4-b59ab4379a72', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '344fe126-0c92-4330-9aa9-0404eaebd401', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('852806f6-10ce-4797-9bb6-cc97d72e6b66', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '066508e8-4663-4866-bf51-379ccc339970', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('9028e0cf-9615-4fa0-b3cc-2bc9c7d476ab', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '785a4a2e-0bcd-482c-b2d9-c16821589486', NULL),
  ('92a56ead-ffb9-47cf-b2e2-d0a8e4bdcc28', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '884ae939-d4ae-4671-9b0f-3b7656efbdfd', 'Core'),
  ('98063eec-3371-48db-ba40-dfa2e319a941', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'aa9b45b1-e526-4cd4-91e5-24da8858ffd5', NULL),
  ('99690d7a-3ce7-4b1b-8fea-4e1297558689', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'fd16ae8e-3345-41b8-8d24-2caac177203e', 'Vertical #1. Computing Technologies'),
  ('9add6e96-e652-4ed9-bff8-a6629e961583', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'fd9dcd6e-e90f-4588-9e94-a688dc0ec078', 'Core'),
  ('9d6eda56-10d9-4858-9809-9dac8d3592fd', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '3d0a68c9-eed8-4bb0-9ac2-68c76f2b8174', NULL),
  ('9d7ce662-fffd-458e-94ca-b552914bd8cd', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '044a8d22-1ab3-470c-a31b-9502e3fd3e1e', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('a209d402-1398-482a-b890-baa9a345e281', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '01b7e779-72a6-4ea7-b565-58e79de7fda3', 'Core'),
  ('a5a76834-b2cc-4935-bfa3-26ea2a7d26aa', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '7736a08d-0e38-4e98-a79c-07bb772026e3', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('aa00d31a-d143-41e1-ba85-c1df36827c45', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '49ceef18-e0f4-491b-bdf6-79d9ec567ffa', 'Core'),
  ('b06cb011-655b-49ff-bb33-63791b25f62a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '9754ebb5-af62-419e-bac4-bfb44ab82487', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('b3a873f1-4c5f-40cc-98bc-480edd7ba2e7', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'b1698209-f018-4335-9f9e-bf8d2b2526b9', NULL),
  ('b6e8ff4c-5531-42d9-90fb-22b091a846b2', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '2b345857-dedb-4088-84b8-70aad49f785d', 'Core'),
  ('ba21f8b1-d072-4a81-bafd-fcb371a45054', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '1d1efd38-bce5-48a2-9058-10cb7c247163', 'Core'),
  ('c1048973-6306-46f2-9414-f2060df85bbc', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '5c7338ca-a012-4678-a7e7-e455bdc05c56', 'Vertical #1. Computing Technologies'),
  ('cda4417b-0c5e-409e-a7bb-c2e5e79e569a', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '9ebf8742-2601-4e39-828d-4c02923ca567', 'Vertical #1. Computing Technologies'),
  ('cf6b683c-2a0e-49da-aae9-3cb849b0d8de', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '189d04fe-ad50-4a2a-ab98-a4c47b5cc919', NULL),
  ('d0dfc376-8fc9-427d-bc7a-92c6d7cb4c06', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '029c81fe-1930-408e-b3ac-4a50b221b4ba', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('d5cebcd8-54a5-42bd-ac23-3cb18dc14487', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'b3f9affc-7281-458a-8dbc-a0893d75fb5b', 'Core'),
  ('da8edf0d-385f-48de-a1a6-5da4e418f22d', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '9a130c8e-7d60-4972-a2b9-16811bb17253', NULL),
  ('dc939e95-20e5-4a1b-8261-966dd92cf551', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'b48a738b-0475-42cf-b186-da4a12f635bb', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('dcc94f67-565d-4886-ac7f-2f5464c10e45', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'df6254a1-231a-4227-8cab-d1d3e9d0eed3', 'Vertical #1. Computing Technologies'),
  ('dd3a6cf3-f00f-4de0-9da2-e27aa94a6ea2', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '72f07a48-26cc-4ee7-b294-7596c3e2245a', 'Core'),
  ('de18d258-3078-44d1-b2a2-15f35a5ef125', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '8ddcf363-6352-439c-bae0-38cc4aa523e6', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('e0703726-0cd1-4b65-a5e9-ba0188ae88e1', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'afcf443e-27db-4650-984b-fd102d246155', 'Core'),
  ('e674e8af-6703-4ef7-a448-9f59de5503f6', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'd54ccb9f-1100-45b8-89c6-2287b1c78f04', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('ee4f501f-ce8e-4491-bf9c-35cc5eb2ebe9', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '089439a0-d127-4764-a6ef-636a9edc34d0', 'Core'),
  ('ef321b17-48e8-4d8a-8bb6-be04d0120fc7', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'f19a2eaf-a192-473e-bf3a-80b395af6ea6', 'Core'),
  ('efca5de6-2caa-42c8-9449-aef84eaf8b50', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '8562bf9b-54d1-4f06-b9e8-51eb3a238da7', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('f1deaf0e-495e-4390-8239-85c726d34301', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'abb22704-f304-4c68-b0a4-c97f954367ba', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('f31b1fbb-563a-4a8f-a520-afd3f56f664f', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '641717a3-d1af-433f-adcf-964aa75e72c8', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('f4140046-2868-4d1d-a91f-1be8559ebfd2', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'f6fda3bb-73de-4adf-8878-9414232e7a49', 'Vertical #3. Digital Financial Transactions and Risk Management'),
  ('fa13a550-9a95-4279-beaa-b035a0ed3b51', '0f10fcf0-90f9-4ace-9d99-c665a796befb', '481c85ab-36d0-43c0-b639-ebf8b6a7ec6e', 'Vertical #2. Financial Data Analytics and Intelligence'),
  ('fc2c3996-17ea-4e50-b0a7-9ea707955f65', '0f10fcf0-90f9-4ace-9d99-c665a796befb', 'bafe725e-87e3-4e6d-9e5a-4f61aed5d8a5', NULL);

insert into student.course_departments (course_department_id, course_id, department_id, department_role) values
  ('05fcde4b-cb01-41af-b6a9-d2176d7dd821', 'b5ccd84c-fef6-4a9a-9e07-8cb988d9bb8a', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('070193c6-7003-4648-95d9-20d831e02989', '9754ebb5-af62-419e-bac4-bfb44ab82487', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('08849cdd-0252-4cb6-ba64-2425fd9180b9', '951cc694-e258-41ea-99d2-08a1b401505a', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('08c8adcd-f175-499b-a204-1ffbf2ec202c', '04b41cd9-a882-48a9-90f2-c1eb380ca815', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('0bece94d-1083-4f25-8a1c-62f59bbcc34b', '6ac79d0e-87b7-4f49-b190-046f1303a48a', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('10dcc958-4a35-45ad-9acd-59f5b6ff7691', 'cf1e5037-b7b0-4e69-b355-74d2b8e802b5', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('117c7491-6635-43ac-a818-19d2d9c2b731', '641717a3-d1af-433f-adcf-964aa75e72c8', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('12acd1be-483a-4188-ad9e-ec158c3be3df', 'aa9b45b1-e526-4cd4-91e5-24da8858ffd5', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('12c72561-ee14-4d53-8778-4de64ced39d1', '8b1aec50-2ea3-4737-8b36-b63d702f5f01', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('1bab87b4-76cd-494a-b321-78241af67e28', '481c85ab-36d0-43c0-b639-ebf8b6a7ec6e', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('2758e19a-fab7-4e2c-b733-3c11af23a15b', '8ddcf363-6352-439c-bae0-38cc4aa523e6', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('2a263b6b-0fe4-46a1-be35-6823da3cbf61', 'bafe725e-87e3-4e6d-9e5a-4f61aed5d8a5', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('347d58af-7782-4ac4-8bcc-d271d48adb3c', '49ceef18-e0f4-491b-bdf6-79d9ec567ffa', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('3c6e5b61-1f5a-42fb-97ac-e5b7256ee317', 'b48a738b-0475-42cf-b186-da4a12f635bb', 'b4febcd3-7b79-4508-a754-867cd8f85a65', 'Contributing'),
  ('3cf3273f-0c8b-494f-9409-a9cf3e8d13e4', 'abb22704-f304-4c68-b0a4-c97f954367ba', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('4242f4bf-c879-4f26-848c-bb46621f0e4f', 'fd16ae8e-3345-41b8-8d24-2caac177203e', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('4383761c-d637-4c58-b644-3cfed0722152', 'c4bee792-ac43-4251-969b-6b6386afa5fb', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('44a83a72-3991-4d16-a3c4-180e09ed3e2a', '044a8d22-1ab3-470c-a31b-9502e3fd3e1e', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('475e7eaa-eaa1-4ce5-a2c3-dbddb7c7973b', '72f07a48-26cc-4ee7-b294-7596c3e2245a', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('4855ccec-eb36-4044-95c4-1b64785c7577', 'cdc5d3c2-c0e8-4f5a-a7a0-0153dc08e39a', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('490514f7-826a-4efa-a663-d93e0757dfe7', '066508e8-4663-4866-bf51-379ccc339970', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('4a4f4dcb-fca7-4d61-8d8e-e99b02268144', '32a621d9-80e5-4d43-82d3-8e642a611420', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('4d45f331-bc68-4107-b5eb-4cfa5e0c4331', '4bbb24c8-1d5e-4463-b710-53f7c06ce12e', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('4ec10967-c495-4d77-8e2b-fe5806f37231', '344fe126-0c92-4330-9aa9-0404eaebd401', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('4ef0a20b-ffa5-4ee5-a5ca-826dcbf03506', '420fea4a-e37c-4a26-ba15-dbf8198c51c2', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('4fc577ca-beff-4af7-9fae-ac3ba4d2c5d0', '8562bf9b-54d1-4f06-b9e8-51eb3a238da7', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('5290ce61-8c9b-4695-869e-78e98d291e0a', 'ab6049fc-b642-4837-b3f1-af5b270e13a3', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('55dd06fc-934c-44d9-ad78-0b7566a87b15', '803a60c0-9f8c-475d-b75e-b2c1100a7eb4', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('5e639088-f938-4020-b70d-d82d58216e78', '3d0a68c9-eed8-4bb0-9ac2-68c76f2b8174', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('626b1f50-649c-4899-9479-18ea83f0e2c9', '7d6bfa93-abd2-4d68-96c2-e0a6694c38fb', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('655022ac-08d5-4de5-92c5-f43737c75817', 'b67dc8a7-8715-4613-a051-591483d92943', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('67becfe5-5233-4769-8ac2-1185c03a7da9', '089439a0-d127-4764-a6ef-636a9edc34d0', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('6bc24d76-9043-4fc1-892f-939a7c63cf00', 'faa6f208-e798-43f9-9bc3-76d80f371299', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('6c3cbc56-50f0-4a50-8548-82e2a6c6c125', 'b3f9affc-7281-458a-8dbc-a0893d75fb5b', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('6c67907d-d229-4648-9293-d181225e465e', '3dfc16dc-58d3-40c2-806b-a564b471f044', 'b4febcd3-7b79-4508-a754-867cd8f85a65', 'Contributing'),
  ('70b0fe24-1a30-4fe2-8583-45031a21e823', '1f457741-c777-4a9d-8fa9-949ea9c30c4f', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('71c57b83-7f88-4a99-9eed-eec3035fa0c4', 'afcf443e-27db-4650-984b-fd102d246155', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('789c7154-7430-4348-99c7-840f1ba61ee0', 'a7f35bc7-8308-4ed5-9175-3ef418e00540', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('7b44996d-62e2-45f2-9798-5b663e57fcb5', '9a130c8e-7d60-4972-a2b9-16811bb17253', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('7d9d67c1-12bc-433f-81f6-57c3adddda47', 'e96f8b34-5158-415b-bfe4-46cb3bd629db', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('7e804c63-946f-4690-836e-3b6ea016e375', '69c64c7b-3a3e-4f1c-ae37-65cf66ee16de', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('820a3e99-e8db-4387-a0ba-2fbb61463352', 'df6254a1-231a-4227-8cab-d1d3e9d0eed3', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('82885da0-2c40-4e9a-aa88-5fcc0685b36b', 'fd9dcd6e-e90f-4588-9e94-a688dc0ec078', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('8983b9d9-7ae0-4ab9-bf58-65020ba0ce60', 'af38b641-6906-478a-b5c0-a0711bf34136', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('8cf010b7-a49d-4efc-957d-bf25744e71bb', '5c7338ca-a012-4678-a7e7-e455bdc05c56', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('91c55b69-7dfb-418b-b818-47675817aaeb', '94c121fe-7900-495b-a0a6-145074ad8691', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('9c6415a8-f4ec-4c6a-9926-6a8f96028489', '1d1efd38-bce5-48a2-9058-10cb7c247163', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('a04df494-280c-43ba-b790-5f41c29a0478', '3aef48f6-28a8-4ff9-a323-1e51898ec22a', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('a3d19b5c-f49a-4864-8bf8-59b30c6443a0', 'f6fda3bb-73de-4adf-8878-9414232e7a49', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('af1680d0-0ae3-4eca-a940-718798dda6a4', '4b19abc5-a143-430e-a961-083974d30a0a', '6b2d519d-f687-4e15-85a4-0ac020cf3da8', 'Contributing'),
  ('b119c391-0b6f-4b7a-82c5-fe0044c4f77a', 'e298be5e-fc53-499d-8fba-f1a819f6d92f', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('b18823f3-bafb-4668-99c3-ea371855d123', 'ce9cde39-47d2-4eb3-b1ff-02fa78c92c53', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('b25373c4-7ee9-4659-9466-2068c17744df', '029c81fe-1930-408e-b3ac-4a50b221b4ba', 'b4febcd3-7b79-4508-a754-867cd8f85a65', 'Contributing'),
  ('b77360fe-6dfb-48e9-a19c-100008dd617d', 'f19a2eaf-a192-473e-bf3a-80b395af6ea6', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('ba0709da-f9ab-44ca-9ad8-b4d40cf91151', '0153ee0b-e1fa-4c40-87de-0829f03461bb', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('bb771902-ab74-4d38-800e-7ac321015147', '4d30a936-4c42-4f6f-80d4-6c62a5933f9c', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('c35668b9-7ffc-449f-98af-fafca2030690', 'bd86d393-6062-4d30-ad29-f0e3cedd43bd', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('c6c1631a-1134-45cb-ba6c-da8f917745d1', '9ebf8742-2601-4e39-828d-4c02923ca567', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('cb7239e4-2a65-454f-bef7-ff5a6ce05821', '7134a9c4-eaa2-4712-80f9-208ae0db6114', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('cbed24d8-01db-4be4-ab77-64b2db48d5c7', '2b345857-dedb-4088-84b8-70aad49f785d', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('cda98b65-1c8f-4743-b216-f9103f1e3a9d', '884ae939-d4ae-4671-9b0f-3b7656efbdfd', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('ce890f8d-f5a0-4231-ba9e-0e25a45350a4', 'c13f592b-2c2f-499c-bf3f-73e0ca335bb8', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('cf8a0370-04e2-400e-b022-74106466ae71', '01b7e779-72a6-4ea7-b565-58e79de7fda3', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('d51001d9-bce0-4fb5-8e0a-ce6c3fef3a6b', 'd54ccb9f-1100-45b8-89c6-2287b1c78f04', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('df5109aa-2633-4602-b97e-bb4876487cc9', '7736a08d-0e38-4e98-a79c-07bb772026e3', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('df641440-cebb-4b0e-bec3-043783eefcfd', '04685b7d-7e48-40a5-80c5-0a14350872e4', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('e418ab58-960e-47f2-a219-555fa44d3896', 'b1698209-f018-4335-9f9e-bf8d2b2526b9', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('ea953b7e-5cc6-41ea-8323-51a4fc375141', '189d04fe-ad50-4a2a-ab98-a4c47b5cc919', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('fcadfb6f-2d62-4771-8622-7ef21d207ab7', '785a4a2e-0bcd-482c-b2d9-c16821589486', '6460604b-1f14-41a5-9c2f-b8d69fcab26b', 'Lead'),
  ('fd52470e-69ac-41a6-be06-e0e846b52593', '36144042-f35c-4645-ad6e-b9b67e2f1bf3', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('fdc861bb-008c-4ca9-bbbc-fa62277187c8', '6a31dd61-3ab6-44a7-b865-b1da1b8ef26f', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing'),
  ('ff247bc0-3588-4c2d-8a7d-1eb94bbfea4a', '7b22c97c-ccc3-42cb-b62c-4ab2c1064a74', 'd28ab726-a0c2-4eff-853e-2fbc036968b0', 'Contributing');
